
import collections

lyrics="na ga re te ku to ki no na ka de de mo ge da ru sa ga o ra gu ru gu ru ma wa te wa ta shi ka ra a na re ru ko ko ro mo mi e na i wa so u shi ra na i ji bu n ka ra u go ku ko to mo na ku to ki no su ki ma ni na ga sa re zu zu ke te shi ra na i wa ma wa ri no ko to na do wa ta shi wa wa ta shi so re da ke yu me mi te ru na ni mo mi te na i ka ta ru mo mu da na ji bu n no ko to ba ka na shi mu na n te zu ka re ru da ke yo na ni mo ka n ji zu su go se ba i i to ma do u ko to ba a ta e ra re te mo ji bu n no ko ko ro ta da u e no so ra mo shi wa ta shi ka ra u go ku no na ra ba su be te ka e ru no na ra ku ro ni su ru ko n na ji bu n ni mi ra i wa a ru no ko n na se ka i ni wa ta shi wa i ru no i ma se zu na i no i ma ka na shi i no ji bu n no ko to mo wa ka ra na i ma ma a yu mu ko to sa e zu ka re ru da ke yo i to no ko to na do shi ri mo shi na i wa ko n na wa ta shi mo ka wa re ru mo na ra mo shi ka wa re ru no na ra shi ro ni na ru na ga re te ku to ki no na ka de de mo ge da ru sa ga o ra gu ru gu ru ma wa te wa ta shi ka ra a na re ru ko ko ro mo mi e na i wa so u shi ra na i ji bu n ka ra u go ku ko to mo na ku to ki no su ki ma ni na ga sa re zu zu ke te shi ra na i wa ma wa ri no ko to na do wa ta shi wa wa ta shi so re da ke yu me mi te ru na ni mo mi te na i ka ta ru mo mu da na ji bu n no ko to ba ka na shi mu na n te zu ka re ru da ke yo na ni mo ka n ji zu su go se ba i i to ma do u ko to ba a ta e ra re te mo ji bu n no ko ko ro ta da u e no so ra mo shi wa ta shi ka ra u go ku no na ra ba u go ku no na ra ba su be te ko wa su wa su be te ko wa su wa ka na shi mu na ra ba ka na shi mu na ra ba wa ta shi no ko ko ro shi ro ku ka wa re ru a na ta no ko to mo wa ta shi no ko to mo su be te no ko to mo ma da shi ra na i no o mo i ma bu ta o a ke ta no na ra ba su be te ko wa su no na ra ku ro ni na"
lyrics="na ga re te ku to ki no na ka de de mo ge da ru sa ga o ra gu ru gu ru ma wa tte wa ta shi ka ra a na re ru ko ko ro mo mi e na i wa so u shi ra na i ji bu n ka ra u go ku ko to mo na ku to ki no su ki ma ni na ga sa re zu zu ke te shi ra na i wa ma wa ri no ko to na do wa ta shi wa wa ta shi so re da ke yu me mi te ru na ni mo mi te na i ka ta ru mo mu da na ji bu n no ko to ba ka na shi mu na n te zu ka re ru da ke yo na ni mo ka n ji zu su go se ba i i no to ma do u ko to ba a ta e ra re te mo ji bu n no ko ko ro ta da u e no so ra mo shi wa ta shi ka ra u go ku no na ra ba su be te ka e ru no na ra ku ro ni su ru u go ku no na ra ba u go ku no na ra ba su be te ko wa su wa su be te ko wa su wa ka na shi mu na ra ba ka na shi mu na ra ba wa ta shi no ko ko ro shi ro ku ka wa re ru a na ta no ko to mo wa ta shi no ko to mo su be te no ko to mo ma da shi ra na i no o mo i ma bu ta o a ke ta no na ra ba su be te ko wa su no na ra ku ro ni na"
lyrics="O shi e te yo o shi e te yo so no shi ku mi o ku no na ka ni da re ka i ru no Ko wa re ta ko wa re ta yo ko no se ka i de ki mi ga wa ra u na ni mo mi e zu ni ko wa re ta bo ku na n te sa i ki o to me te freeze ko wa se ru ko wa se na i ku ru e ru ku ru e na i a na ta o mi tsu ke te yu re ta yu ga n da se kai ni ta ta bo ku wa su ki to o tte mi e na ku na te mi tsu ke na i de bo ku no ko to o mi tsu me na i de da re ka ga ka i ta se ka i no na ka de a na ta o ki zu tsu ke ta ku wa na i yo o bo e te te bo ku no ko to o"
lyrics="Shi ji ma no so ko ka ra Me za me ru so no ha shi ra ta chi to ki wo ko e Shi n ku no chi shi o ga ta chi a ga ru yu u ki wo Hi ki a wa se ru  U ke tsu gu ai wo sa da me to yo bu na ra Ho ho e mu me de tsu gi no te wo  Ya mi wo a za mu i te se tsu na wo ka wa shi te Ya i ba su ri nu ke ya tsu ra no su ki wo tsu ke Tsu ra nu i ta o mo i ga mi ra i wo hi ra ku Ke tsu mi a ku ni ki za mare ta in ne n ni U ki a ga ru ki e na i ho ko ri no ki zu na ni gi ri shi me te"

a=lyrics.split()
print(a)
a.sort()
print([item for item, count in collections.Counter(a).items() if count > 1])